In [26]:
#Buatlah sebuah fungsi untuk membuat matrix berdasarkan input dari user
print("Fungsi matrix berdasarkan input dari user")

#Tulis kode kamu disini
def create_matrix(baris,kolom):
    matrix = []
    for k in range(baris):
        baris_matrix = []
        for p in range(kolom):
            element = int(input(f"Masukan element matrix[{k}][{p}] :"))
            baris_matrix.append(element)
        matrix.append(baris_matrix)
    return matrix

baris = int(input('Masukkan Jumlah Baris:\t'))
kolom = int(input('Masukkan Jumlah Kolom:\t'))
create_matrix(baris,kolom)


Fungsi matrix berdasarkan input dari user


[[7, 9, 6], [8, 1, 3]]

In [38]:
#Buatlah sebuah fungsi untuk mencari invers matrix berdasarkan input matrix dari user

import numpy as np 

#Tulis kode kamu disini

def create_matrix():
    baris = int(input("masukan jumlah baris :"))
    kolom = int(input("masukan jumlah kolom :"))
    matrix = []

    for x in range(baris):
        barismatrix = []
        for y in range(kolom):
            element = float(input(f"masukan element matrix [{x}] [{y}] : "))
            barismatrix.append(element)
        matrix.append(barismatrix)
    return matrix

def invers(matrix):
    try:
        invers_matrix = np.linalg.inv(matrix)
        return invers_matrix
    except np.linalg.LinAlgError:
        return "invers matrix tidak ditemukan "

matrix = create_matrix()
invers_matrix = invers(matrix)
print("matrix   :\n", matrix)
print()
print("invers   :\n", invers_matrix)


matrix   :
 [[5.0, 4.0, 7.0], [8.0, 9.0, 1.0], [2.0, 4.0, 3.0]]

invers   :
 [[ 0.184  0.128 -0.472]
 [-0.176  0.008  0.408]
 [ 0.112 -0.096  0.104]]


In [28]:
#Buatlah Fungsi untuk melakukan pembagian matrix antar matrix berdasarkan input user menggunakan nested loop

def bagi_matrix(matrix1, skalar):
    hasil = []

#Tulis kode kamu disini
return hasil


def bagi_matrix(matrix1, skalar):
    hasil = []
    for x in range(len(matrix1)):
        row = []
        for y in range(len(matrix1[0])):
            fungsi = matrix1[x] [y] / skalar
            row.append(fungsi)
        hasil.append(row)
    return hasil
matrix1 = [[3,5,9], [6,7,4], [5,1,9]]
skalar = int(input('Matrix dibagi berapa?\t'))


hasil_bagi = bagi_matrix(matrix1, skalar)
print(hasil_bagi)

[[1.5, 2.5, 4.5], [3.0, 3.5, 2.0], [2.5, 0.5, 4.5]]
